### ISSUE TITLE
User agent hasn't been updated

### ISSUE THREAD

**Issue by luke-jr** [btc1/bitcoin#55] opened 2017-07-01 19:36 UTC
The btc1 beta is still claiming to simply be "Satoshi" (Bitcoin Core). This should be updated so people can more reasonably distinguish between the two.

**Comment by NiKiZe** [comment] 2017-07-01 20:33
Seems like duplicate of #25

**Comment by happyconcepts** [comment] 2017-07-01 23:19
Version number was bumped.

**Comment by mpatc** [comment] 2017-07-02 02:38
What are the advantages and disadvantages of allowing people to more easily distinguish between the two? Seems like a bit of work for little expected benefit.

**Comment by jli225** [comment] 2017-07-02 18:38
Well, @luke-jr came here to troll us again. It's such poisonous liars that made the Core corrupt completely. Good guys left one after another. Only unashamed clowns still stay with Luke in the Core Committee.

For anyone who has not known yet, @luke-jr is a blatant liar and full-time paid shill of notorious Blockstream.

I agree that the current Core Committee shall change the name of their vision since they no longer follow Satoshi's vision and they tell lies to defame Satoshi & Gavin & Mike Hearn regularly. Also, @luke-jr shall not claim itself as "Bitcoin dev" to confuse newbies.

Maybe the Core Committee need rename as "UASFCoin Core"? Wow users, sounds great, although it's "Fake users".
 
Update: Blockstream uses many new accounts with weird names to upvote/downvote. Such liars call themselves as "Bitcoin devs". LMAO.

**Comment by Zaromet** [comment] 2017-07-02 19:31
I think that would add attack vector to nodes. DDOS...

**Comment by Pheromon** [comment] 2017-07-02 19:33
@luke-jr: jli225 is right.
You have every right to pursue your personal coin preference, and if you happen to be fine with a 300K block please do so.

Just leave the name Bitcoin for the project that Satoshi envisaged, where miners compete in the free market by processing big blocks with many thousands txs with very low fees for users.

We subscribed to that project, and we would like to keep it that way, thanks.

**Comment by jli225** [comment] 2017-07-02 21:42
This troll post shall be deleted and @luke-jr deserves a ban for telling lies and being poisonous.

I believe usually policy is to delete obviously-misinformed-FUD-trolling. No need to close/reply.

To test, I submitted a similar post to that blockstream-hijacked repo, and in minutes was it not only closed but also deleted by a Blockstream staff.

**Comment by luke-jr** [comment] 2017-07-02 21:45
The only trolling/lying here is from @jli225 and @Pheromon

**Comment by hoffmabc** [comment] 2017-07-02 21:48
Children. Can't there just be a focused tech conversation? This is ridiculous.

**Comment by eumartinez20** [comment] 2017-07-02 23:02
If you would like to remove Bitcoin Core devs from Bitcoin you may at least not steal their name to make your distro seem legit.

**Comment by jli225** [comment] 2017-07-02 23:15
@eumartinez20  Sad to see that you have been brainwashed.

Anyone is welcome to Bitcoin. No one can remove you from Bitcoin. No one can force you to be in Bitcoin.

Satoshi and Gavin are the most legit names for Bitcoin community.

Bitcoin is an open-source project. Satoshi is the creator. Satoshi gave all the useful resources including GitHub/Bitcoin to Gavin when he decided to leave. Gavin saw those recourses as public resources and he never wanted to be any kind of dictator, so Gavin passed the resources to Vladimir. That's a huge mistake, to some extent. Because Vladimir is the wrong people, who see GitHub/Bitcoin as a private property he must grab tightly. It's with the help of Blockstream that Vladimir successfully hijacked the repo, so Vladimir agrees with BS on everything, including the notorious patents. The interest and patents of BS are built on sidechains, so they try to cripple the main chain with endless lies and propaganda.

Before you defame this project, Bitcoin community, and all of us, you shall at least inform yourself about Satoshi's vision thus you could tell who really try to steal the name while seeming legit. It's Satoshi's vision that gathers the majority to protect it.

The only soul behind this project is: We love Bitcoin.

**Comment by HashSquatch** [comment] 2017-07-02 23:20
@jli225 Gavin, the guy who said Craig is satoshi? Stop attacking people on a personal level. This is a github repo, not /r/btc.

**Comment by eumartinez20** [comment] 2017-07-02 23:25
The Bitcoin community is not represented by a few companies.
The Bitcoin community will decide what's best for Bitcoin even if bad actors try to influence and take over power.
This invitation only project spends more time talking about other projects and companies than fixing bugs and improving itself.
And please check your sources, you have been brainwashed.

**Comment by glebedel** [comment] 2017-07-02 23:31
@jli225 some people come here to see issues, PRs raised and discussed and track how the project is coming along. You come off as quite seriously unhinged and this harms the btc1 project more than anybody else or any other clients. Like it or not, plenty of people back core and their devs. There is some kind of agreement where people from both sides want to find common ground in this project. With every comment you make you drive away competent devs and potential backers. 

This is not the right avenue to peddle conspiracy theories and plain aggressiveness to people contributing and discussing fair technical points (like a user agent).

On that note, coming back to tech argument: being able to distinguish segwit2x nodes can be useful to understand how used and potentially reliable the client is. As discussed previously, danger of ddos is probably real but I'm not sure it's avoidable especially since in the end the version bump change can still be used by attackers to target this client.

**Comment by mbelshe** [comment] 2017-07-02 23:48
segwit2x should be non-differentiable from any other node.  this is sort of like the browser wars - everyone still claims to be mozilla, even chrome.  given the hostile bitcoin network, this is even more important for compatibility and safety.

**Comment by jli225** [comment] 2017-07-02 23:48
@FedoraTipper Personally, I didn't and don't think CSW is Satoshi. Fortunately, Gavin said he had been embezzled later. It's not only personal attack but ill-intentioned to regularly slander Gavin for this regularly, after more than one year. Unless you did not do anything wrong in the past, like some self-righteous guys.

r/btc is far from perfect. However, it's much better than that censored reddit sub. If you haven't realized that, please open your eyes.


@eumartinez20  I had same feeling with you months ago, maybe worse.
It looks like you repeated some propaganda of BS. That's fine, yet half-truth. If you have any knowledge about “separation of powers” mechanism, you will realize how ridiculous those propagandas are. In cryptocurrencies world, users don't have many ways to show power **directly**. For most users, the only way is to vote with feet. And now we all know how they voted with feet. 

"The Bitcoin community is not represented by a few companies.“ That's always correct. But, the hashrate majority and economic majority certainly CAN represent users, since users can't represent themselves in any other way. That's the theoretical basis of any UASF. And that's why we call the BIP148  "fake UASF".


@glebedel I certainly try to avoid such talks. However, this issue submited by @luke-jr isn't any issue, technical or non-technical, but trolling only. Anyway, if you submit similar issues to any repo in GitHub, it will be closed immediately. The mods here try to be as tolerant as possible. That kind attitude gives such kind of trolls a chance to show their evil will.

**There is no necessarity for this project to do any other thing to distinguish nodes, because this repo will become the new reference repo. It's the obligation of current Core to change if they want to distinguish their nodes from ours, because they are minority and they have the obligation to change name to inform their followers that they are no longer the reference client. Yet, I don't think they have the moral level to do so.**

**Comment by mbelshe** [comment] 2017-07-02 23:49
propose we close this as will-not-fix.

**Comment by nyhele** [comment] 2017-07-02 23:53
What is the matter with @jli225 in one instance he is busy attacking luke-jr and other devs on github, the other he is busy saying how everyone is welcome in bitcoin. 

On topic: Why will this not be fixed? To me it seems as if you wish to be independent but are afraid to take the step. I am aware that you will hardfork at some point, in which case things are going to get even wierder if you dont user a proper user agent imo. It just seems half-assed to not do it tbh.

**Comment by eumartinez20** [comment] 2017-07-03 00:00
I still think we should differentiate this client from others:
  - It is another implementation, it was specifically one of the goals of this project
  - The nodes can still be DDOSed without further difficulty.
  - The UA can be confusing for users (unless this project counts on users being mistaken on purpose)

I dont see any reason why this should not be fixed, please share if I missed anything.

**Comment by glebedel** [comment] 2017-07-03 00:04
@jli225 
> It's the obligation of current Core to change if they want to distinguish their nodes from ours,

Core doesn't have to do anything. All other implementations tried to distinguish themselves through another user agent, BU, XT, classic, bcoin, bip148 etc.. **Not sure what is the technical argument that requires segwit2x to be any different.**

> because they are minority and they have the obligation to change name to inform their followers

Minority of what? Currently core clients are the one ran by most listening nodes, non listening nodes  & hash power.

> that they are no longer the reference client.

Not sure what you measure for reference client but like said before they currently are the client run by the majority of the network. Whether segwit2x will become the reference client or not is to be seen but in any case you can't force core to do anything on their own repo...

@mbelshe yet chrome still adds `chrome` to its user agent strings does it not?

This is really trivial and would help in gaging what kind of support segwit2x has which is good for everybody, supporters or detractors. **For now** it's distinguishable through version number but that's actually confusing since as far as i'm aware it wasn't rebased and doesn't contain core's 0.14.2 improvements.

**Comment by opetruzel** [comment] 2017-07-03 00:06
@mbelshe
Is DDoS protection the only reason for your Nack? If so, I think that security through obscurity might be rather futile if/when there are still other simple ways to distinguish this client from others -- version#, bit signals, future DNS seed lists, etc.

For that reason, is it really worth trying to hide in plain sight with a shared user agent string? I'm still undecided.

If you have other reasons for the Nack, please share so that we're all armed with that info before we make our individual decision on this one.

**Comment by jli225** [comment] 2017-07-03 00:09
@nyhele I suggest you take some introductory psychology courses to know about cognitive dissonance. Some economic courses would be better.
Anyway, Bitcoin is far beyond the codes. Possibly that's the reason why Bitcoin was not created by "code experts". 
No offense to ~~codes~~ devs. We are all ~~codes~~ devs, expert or not expert.

@glebedel Current Core did not change the name of clients after either they no longer followed the vision of Satoshi or they were no longer under the supervision of Gavin, did they? 

Not sure what is the technical argument that requires current Core to be any different. You can ask them to do so. It's good for both of us.

If there is only one person who can use the name, it is Gavin. SegWit2X as the new reference client not only has the right, but also has the obligation to be "Bitcoin" and "Satoshi", instead of "Bitcoin XXX" "Satoshi XXX".

**Comment by opetruzel** [comment] 2017-07-03 00:18
@jli225 
Can you please refrain from political statements and stick with strictly technical discussions relevant to the Issue or PR? I respect your thoughts and opinions on those issues, but this is not the time or place for those types of discussion. Thank you ahead of time!

**Comment by mbelshe** [comment] 2017-07-03 00:18
Let's focus on core functionality before worrying about labeling.

**Comment by RHavar** [comment] 2017-07-03 00:19
@jli225 Your behavior here is highly inappropriate, and frankly embarrassing. This issue is about a custom user agent. If you can not stay on topic without attacking people, please do not participate.

**Comment by glebedel** [comment] 2017-07-03 00:26
@jli225 
> Current Core did not change the name of clients after either they no longer followed the vision of Satoshi or they were no longer under the supervision of Gavin, did they?

What are you even on about? The core repo stayed the same, the user agent stayed the same. 
 Segwit2x is a more recent client and like all 'recent' client, it's quite logical it has a separate user agent. Arguing about the 'vision of satoshi' is ridiculous and a moot point since neither you or me should try to interpret what it is/was and this forum is definitely not the right place to do that.

I do understand argument in the line of risk of DDOS and it's definitely a valid point since it's been reported that other nodes have been DDOS'd in the past. However i'm not sure that obscuring user agent is a good way to avoid DDOS for that especially since it can be targeted through major version.

@mbelshe I'm not sure anybody is saying it's a huge priority. Doesn't mean it shouldn't be discussed either and it seems contained in its own issue so shouldn't impact other work...

**Comment by jli225** [comment] 2017-07-03 00:32
@mbelshe  Agree. Let's focus on core functionality before worrying about labeling. This issue may be considered in the future, maybe decades, when this new decentralized reference repo becomes visibly corrupt too. That's inevitable.

@glebedel Everything is changing constantly. The only thing that does not change is change itself. So if you thought it "stayed the same", that's because you had no clue about how it changed.

@RHavar Thanks anyway.

**Comment by hoffmabc** [comment] 2017-07-03 01:00
This whole issue is purely political. The only reason to change it is to make a statement. If you can detect segwit2x in other ways then there is no reason that nodes who need to can't just do so. This is a cosmetic change that makes no difference whatsoever.

**Comment by jameshilliard** [comment] 2017-07-03 02:28
> segwit2x should be non-differentiable from any other node.

It already is differentiable(using the main version number), [my PR](https://github.com/btc1/bitcoin/pull/56) just makes the distinction obvious to anyone looking at peer subversions.

>  this is sort of like the browser wars - everyone still claims to be mozilla, even chrome. given the hostile bitcoin network, this is even more important for compatibility and safety.

Bitcoin nodes are not supposed to use subversion for feature compatibility/advertisement, that's what service bits and protocol version are for.

**Comment by fomosapiens** [comment] 2017-07-03 06:32
i definitely want distinction. i want to avoid anything that jgarzik, gavin and his cartel got to do with.

**Comment by Pheromon** [comment] 2017-07-03 06:35
So what are you doing here?
If you want a client that distances more and more from Satoshi vision and render itself irrelevant just stick with core.

**Comment by jgarzik** [comment] 2017-07-03 06:41
Closing - duplicate of #25 - also locking comments.

Ladies and gents, please keep the conversation focused and technical.

**Comment by eumartinez20** [comment] 2017-07-03 06:41
Yes, the name seems to be political. I must warn you, this project using that name may fool a couple users into downloading it but will be fully rejected by hundreds just for trying to take over Core reputation.

These are the same evil ways we have been seeing in the Bitcoin community for a couple years and did not win anyone over. Please try to start doing things rightfully to get honest support.

I have not seen yet a sound reason to not change it, only political ones....still waiting....

**Closed as completed** 2017-07-03 06:41 UTC
