### ISSUE TITLE
Opt-in segwit2x-only transactions

### ISSUE THREAD

**Issue by RHavar** [btc1/bitcoin#125] opened 2017-09-25 17:43 UTC
I understand there are objections to comprehensive anti-replay measures, as it will break compatibility and invalidate previously valid transactions (such as those that are timelocked).

However as it stands, as a bitcoin business segwit2x HF will force me to halt all bitcoin activity at the time of the fork until things settle down and it's clear what is the dominate fork to use.

A lot of this pain could be eased by having a slightly different transaction format that is only valid on segwit2x chain. This would allow businesses to continue to operate without risk of accidentally bleeding all their money on the other chain.

**Comment by christophebiocca** [comment] 2017-09-25 17:58
Duplicate of #117.

**Comment by RHavar** [comment] 2017-09-25 18:14
> Duplicate of #117.

#117 is the reverse. It's a transaction valid on the original chain, but not on segwit2x one. There should also be a way to create a transaction that is purely valid on the segwit2x chain

**Comment by christophebiocca** [comment] 2017-09-25 19:20
> #117 is the reverse. It's a transaction valid on the original chain, but not on segwit2x one. There should also be a way to create a transaction that is purely valid on the segwit2x chain

I see what you mean, however once you move your funds on the 1x chain and the transaction confirms, you can then move your funds on the 2x chain and that cannot be replayed on the 1x chain (as the funds have already been spent on that side).

I guess there's the risk of the chain being rolled back far enough that the initial replay-protected transaction is dropped and replaced with a replay of the 2x transaction. On the other hand if long chains are being reverted that easily the 1x chain is unusable for payments regardless of replay protection.

**Comment by RHavar** [comment] 2017-09-25 19:23
> however once you move your funds on the 1x chain and the transaction confirms, you can then move your funds on the 2x chain and that cannot be replayed on the 1x chain (as the funds have already been spent on that side).

The issue is if you're running a business/service, you can't sanely automate this (or at least the amount of complexity makes it totally infeasible) -- which means you can not operate through the fork. If you can make sure every segwit2x transaction you make is not replayable, and every legacy transaction you make it not replayable -- it means it's possible to operate during the fork.

**Comment by sturles** [comment] 2017-09-25 19:50
Agreed.  It would be unfortunate if exchanges have to stop all operations on the S2X chain while waiting for confirmations on the BTC chain, which are required until any coins can be spent on the S2X chain.  This could become a major bottleneck for S2X adoption.

**Comment by jcansdale** [comment] 2017-09-26 03:18
You can do opt-in two way replay protection like this #123 Replay protection on the 2x side doesn't actually require any changes.

**Comment by jheathco** [comment] 2017-09-26 17:07
@sturles if we're worried about confirmations on what you've chosen to refer to as the "BTC" chain we should be focusing much more on how blocks will be found at all given that ~94% of hash power is currently signaling S2X.  I'm not sure if any tickets have been opened with bitcoin core concerning difficulty adjustment or PoW change but it would be at least worthwhile to consider.

**Comment by sturles** [comment] 2017-09-26 17:55
@jheathco You didn't protest when btc1 implemented wipeout protection.  That would be a waste of time and complexity if you were so certain about > 50% hashrate forever.  In fact several of the pools signalling NYA have made it clear they will mine BTC as well, and many of them are mining BCH as well as BTC now.

Anyhow, if S2X manages to get as much as 94% of the hashrate, the chain will be dead for a long time while exchanges and users are waiting for confirmations on the BTC chain to secure their BTC against replay attacks.  Exchanges need to protect their own and their customers BTC, and users need to protect their as well, for the same reason that btc1 implemented wipeout protection.

**Comment by jheathco** [comment] 2017-09-26 18:05
@sturles I didn't protest wipeout protection because there are no major drawbacks to including it - that's not a good comparison.

**Comment by Sjors** [comment] 2017-09-26 18:30
I believe replay protection in this particular direction is useful, see my comment in https://github.com/btc1/bitcoin/pull/117#issuecomment-332290493.

One approach would be to craft a transaction that's invalid, not just non-standard, on the 1x chain and make it both valid and standard on the 2x chain. I floated some ideas [here](https://github.com/btc1/bitcoin/issues/34#issuecomment-324431253).

**Comment by sturles** [comment] 2017-09-26 20:56
@jheathco On the other hand it would be a major drawback to this chain if you require everyone to transact on the BTC chain first, to avoid possible coin loss, don't you agree?  What do you think are the drawbacks of making S2X independent of BTC?

**Comment by jheathco** [comment] 2017-09-26 22:38
@sturles if by making s2x independent of btc you mean implementing opt-out replay protection, you know very well at this point what the major drawback is.

**Comment by sturles** [comment] 2017-09-26 22:50
@jheathco I am discussing this issue, opt-in S2X-only transactions.  Did you misunderstand the subject and issue?

**Comment by Sjors** [comment] 2017-09-27 09:43
My suggestion is also opt-in. The key is to allow, but not require, a new transaction type that’s invalid on the 1x chain.

I believe BCH switched the sighash type to something that’s invalid on BTC. That makes it mandatory protection. Instead of switching you can allow both types. That makes it opt-in.

Instead of the sighash you can break any other rule that makes a transaction invalid on the 1x chain. Two drawbacks that I’m aware of are technical debt and confusing SPV wallets (but only for that opt-in tx type, not for regular transactions).

**Comment by Sjors** [comment] 2017-09-27 09:45
“Break” should be “expand”.

**Comment by dgenr8** [comment] 2017-09-28 00:29
The method used by cash is designed to be reused.  The idea is you would set SIGHASH_FORKID in the hashtype and also check for a specific value (except 0, which cash uses) in the high 3 bytes of the hashtype as serialized, which are currently unused.

A drawback, which shouldn't matter much, is that this only works if there is a signature in some input.

**Comment by bitPico** [comment] 2017-09-29 22:31
NACK
It is highly unlikely that there will be any segwit1x chain with any decent security left after the segwit2x  fork. segwit1x is legacy software (it always has been because it failed to scale the base block size) and it will be abandoned like all out-dated software.

**Comment by bitPico** [comment] 2017-09-29 22:36
@RHavar If you have to halt your system because of this you are doing something wrong and/or not prepared. Our entire infrastructure is SegWit2x ready and nothing needs to be done now or after the fork. SegWit2x will "just work" and SegWit1x will go away like all old software does. The support for SegWit1x is tiny, none of our miner friends will be running old software.

**Comment by sturles** [comment] 2017-09-30 11:50
@bitPico Stop trolling.  This is the old software.  It is 2147 commits behind Bitcoin master, and has know bugs that nobody take care of.  The Bitcoin repository has commits almost every day, while nothing has happened here since July.  To everyone who look, this project seem to be both dead and controlled by one single developer.

I don't see the support you are claiming either.  Not a single one of the exchanges I use every day have stated they will support S2X, even as an altcoin.  Don't trust the miners.  They are mocking the entire circus by signalling /NYA/ on BCH blocks.

**Comment by hardforkmatters** [comment] 2017-09-30 13:11
@sturles Indeed. I have suggested "Hardfork lock-in period #121" 17 days ago to verify miners' intention. Nobody supported.
So, S2x - good luck to you, luck will be required.

**Comment by bitPico** [comment] 2017-09-30 20:02
@sturles  This is btc1 (a 2x implementation).  1x is old outdated software (code commits mean nothing). 1x supporters are trolls here while 2x supporters discuss here. Have a excellent day.

**Comment by sturles** [comment] 2017-10-01 12:28
@bitPico Please point me to a comment where you are discussing instead of trolling.

This software has old bugs and is not maintained.  The project seems dead, and unable to implement anything interesting.  On the other hand Bitcoin Core is under active development.  Proof: The largest pull request here is a rebase to Bitcoin Core 0.15.  QED.

1x may be worse, I never heard of it before.

When btc1 is no longer compatible with Bitcoin in November, as is it's stated purpose (hard fork), exchanges and other services need a simple way to split off their S2X quickly to keep their services running.  My own broker service can certainly not support S2X if I don't have an quick and easy way to split coins into BTC and S2X, without waiting more than 100 blocks for a coinbase transaction to mature and spread.

**Comment by jgarzik** [comment] 2017-10-01 15:33
@sturles Since you did not point to a commit, we cannot know what you mean by "old bugs".

btc1 is on 0.15, which is the latest Bitcoin Core branch as well.

It is obviously not dead, as software changes, issues and pull requests are all actively occurring.

Here are some tutorial resources for git and github, that might help in finding where the changes are occurring: https://help.github.com/articles/git-and-github-learning-resources/

**Comment by sturles** [comment] 2017-10-01 16:46
@jgarzik #103 is an old bug, reported almost 2 months ago.

The default branch, segwit2x, has no commits since July 22nd.  There are other branches.  All branches with recent commits fail travis build.  According to the README files, most branches are Bitcoin Core, including the default branch.  Some are "btc1 Core".

Can you point to some real development on btc1, which is not just copying changes from (the real) Bitcoin Core?  Some improvements, except consensus changes, wipeout protection (because you aren't that sure about getting a majority of the hashrate) and malicious changes intended to cause a major interruption in connectivity when the chain forks (because you don't believe many users will actually switch to btc1)?

**Comment by jgarzik** [comment] 2017-10-01 17:30
@sturles `segwit2x` is the production branch, which is in production bug freeze mode.  `segwit2x-dev` is a development branch.  Look at the development branch.

See https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging for an introduction to git branches.  See https://en.wikipedia.org/wiki/Freeze_(software_engineering) for a description of code freeze.

**Comment by sturles** [comment] 2017-10-01 18:47
@jgarzik Where is it documented what the various branches are for?  Many files in the docs directory refer to the master branch, but this branch does not contain the consensus changes.  The segwit2x-dev branch README file refer to the segwit2x branch, and are you sure https://bitcoincore.org is the appropriate URL?  At least users who are confused can download binaries there, to be sure they don't make any mistakes by compiling the wrong branch.

Bug fixes are usually allowed after a code freeze.  The wallet bug could be fixed.  The dbcache memory usage spike fix is more serious, but the fix is more intrusive with possible side-effects.

**Comment by bitPico** [comment] 2017-10-01 20:53
There is no wallet bug. @sturles broke his wallet file by moving it onto a system that does not support it. Read the BDB documentation @sturles.

**Comment by CosmicHemorroid** [comment] 2017-10-02 06:34
@sturles if @jgarzik wanted people to have easy access to view the segwit2x-dev branch he could have simply posted a link for you. Tells you all you need to know.

I did find this in the ML:

"5. Opening Dev Branch

btc1 as a project will continue after the November hard fork. We will
welcome community changes outside the scope of the SegWit2X project in a
new dev branch at btc1 github.

There are several exciting changes that will be pushed there in the coming
months, including some performance improvements, expanded wallet
capabilities—the bitcoind wallet really is ancient tech—, expanded
functional tests, and a few fun surprises.

If you wish to contribute to the dev branch, please mark github pull
requests with ‘outside SegWit2X scope’ or similar language."

**Comment by drunkenclam** [comment] 2017-10-02 08:28
@jgarzik Even the segwit2x-dev branch also has like 99% cherry-picked Core commits. The commits from other devs are version number changes and things like that. Where is the actual development work that you promised on the ML?

**Comment by sturles** [comment] 2017-10-02 09:24
@bitPico I eliminated that as a possible cause in two different ways.  The file works fine in Bitcoin 0.12 on the same platform, so it must be interpreted correctly by DBD.  To verify further, I dumped the wallet on the original platform, and loaded it on the ARM.  There was no difference in behaviour.  Please post further comments in the correct issue, if you have any useful feedback.

**Comment by bitPico** [comment] 2017-10-02 20:27
@sturles Attach the wallet file and we will prove there is no bug and it is simply a compatibility issue (your own problem).

**Comment by apoelstra** [comment] 2017-10-02 20:53
@bitPico please take this somewhere that it's revelant, or just drop it, it has nothing to do with replay protection.

(Also TIL that you can thumbs-up your own Github comments.)

**Comment by bitPico** [comment] 2017-10-02 21:43
@apoelstra You mean @sturles because he is the one trolling this issue with a wallet non-issue instead of opening a new issue. We were simply letting him know that is the case.

Of course you can thumbs-up your own comments but it has nothing to do with replay protection. ;-)

**Comment by bitPico** [comment] 2017-10-02 22:03
Replay protection for the 2x (majority) chain is not needed as recently proven with Bitcoin Cash. If the legacy chain (1x) continues then they will need to add this. Consider closing this as it is a non-issue with over 92% of the network hash rate supporting (including us) 2x. We have no intentions of altering our original non-satoshi codebase just to maintain compatibility with BTC1. Remember, there is more Bitcoin implementations than just BTC1 that are backing the SegWit2x efforts. If you change your code to become incompatible with our codebase then SegWit2x will lose ~2% of the entire network hash-rate from us alone because you force us and other miners to abandon the 2x efforts. 

It's time to start writing standards track papers and using a working group for Bitcoin like SIP or HTTP. The days of a single codebase implementation are long over folks.

NACK

**Comment by NiKiZe** [comment] 2017-10-02 22:29
@bitPico Classic is so far 2x enforcing, (but it will continue to ignore witness data)
I think what we want is something like #127, but I would suggest that it is deemed non standard and not included in blocks already, that way it can be used to verify which clients that runs compliant code.

**Comment by bitPico** [comment] 2017-10-02 23:02
@NiKiZe 

#127 is not opt-in. It requires other node implementors to add block rejection code in the case of a replay protected transaction.

Over ~88% of all Bitcoin hash rate is non-BTC1 codebase (they are just signaling 2x via version bits with whatever node implementation they run). ~16.5% of that doesn't run Satoshi based code whatsoever including ourselves.

We are reaching a point with Bitcoin where everything MUST be OPT-IN because us non-satoshi code implementations will refuse to write code for the sake of somebody else writing code.

Again, Bitcoin needs an IETF working group moving forward because the current development is several different groups with varying opinions trolling each other first and coding second. The current state is not sustainable development of Bitcoin even in the short-term.

**Comment by sturles** [comment] 2017-10-03 08:19
@bitPico Trolls like you is the reason why signatories of the NYA are withdrawing from it.  I had an intention to support S2X as my first altcoin, thinking I would find a niche since none of the other brokers in Europe will support it, but it turns out this project is hostile to everyone wanting to support S2X.  If I come here and file actual bugs, or explain what I require to support it, I am met by trolls and outright hostility.  The only "development" going on here, is copying from Bitcoin Core and changing names.

I don't care about hashrate.  My node doesn't care about hashrate, other than for difficulty adjustments.  My customers nodes won't care about hashrate, except for difficulty adjustments.  The price doesn't care about hashrate.  BCH has had more hashrate than BTC on many occations, but it is still a failure.  I sold much of my BCH at 0.2 BTC to someone who actually believed the trolls.  It is now more than halved in price vs BTC.  In two months only five of my customers have requested to buy BCH, while I have five every day asking for LTC or ETH.  Miners care about profitability however.  This is the reason why large pools are mocking the NYA signal, and pulling their support from the NYA.  They want to keep their miners after the split.  When all exchanges and brokers, and even competent Bitcoin developers, are met by hostile trolls, there won't be anyone buying S2X.  It won't be supported anywhere.

Keep putting a thumb on your own comments.  Think about why you are the only one doing it.

Unless I have a secure way of splitting S2X from BTC, which will work from the beginning after the fork, I can't support S2X.  It is that simple.

**Comment by jcansdale** [comment] 2017-10-03 11:34
@bitPico,

> #127 is not opt-in. It requires other node implementors to add block rejection code in the case of a replay protected transaction.

It's opt-in for the users but not for the node software. Are you proposing it should be opt-in, in the same way that Segwit is "opt-in"? 😕

**Comment by jgarzik** [comment] 2017-10-04 03:14
Merged #127 (opt-in P2SH replay) and closed #34 (replay tracker).

Leaving this issue open to track efforts to find a 2x-only opt-in method (that doesn't break 10M+ wallets).

**Comment by ethackal** [comment] 2017-10-04 03:24
If S2X is a continuation of the Bitcoin blockchain, rather than an altcoin with a shared history, coin splitting constitutes an attempt to double spend. In this light, enabling and encouraging attacks against the Bitcoin ledger may actually result in more turmoil than not including any replay protection. In fact, it may be better to encourage replay to as great an extent as possible, after all if there is only one Bitcoin, we should desire that the ledger be consistent no matter which branch finds success. It is not possible to stop users from splitting coins using unmatched post-fork UTXOs, but that should be an argument against the legitimacy of the minority branch, not a way to turn one coin into two.

At the time of the fork, there are not two chains, but rather two branches of the same chain. Under the new S2X rules only one of those branches is valid, however, it is not possible to know with absolute certainty which branch the majority of hashrate will choose to extend. The miners have used their unique, sybil-resistant ability to clearly signal an intent to enforce NYA and presumably S2X rules. If the miners are operating in an honest fashion, implementation of S2X is the only legitimate outcome and the S1X branch must be seen as an alternate history of the _same_ ledger, on which continued mining constitutes an attack against the honest nodes. If a majority of the hashrate, having signaled an intent to implement NYA/S2X instead mines against the S1X branch, then they have demonstrated their dishonesty. If the majority of the Bitcoin mining nodes are dishonest, the appropriate response is a fork to a new proof-of-work.

Instead of implementing opt-in replay protection, I suggest that efforts would be better spent finding ways to encourage transaction replay across the branches. It is a stronger stance to say that this hard fork is not an opportunity to split coins and increase holdings. When the dust settles, there should be only one honest ledger, that with the most proof of work behind it, performed by nodes that signaled and followed through with their honest intentions.

**Comment by autemox** [comment] 2017-10-04 05:04
I am glad replay protection was implemented.

I noticed that the mempool is empty in Bitcoin.  What exactly is the purpose of creating 2xcoin?

I recommend choosing a plan for the future and implementing 2xcoin when it is more appropriate:

WHEN AVERAGE BITCOIN SEGWIT TRANSACTION FEE EXCEEDS $10:
SET A DATE FOR 2XCOIN TO FORK 6 MONTHS FOLLOWING

This would give plenty of time for everyone to update and you will get user support for the update.

**Comment by matsjj** [comment] 2017-10-04 09:32
@jgarzik Thanks for merging the one-way replay protection!

The proposals by @Sjors would actually provide a way for 2-way replay protection, opt-in, that could be easy to implement into any wallet that wishes to provide this. 

This won't break anything, it would be completely opt-in, and the diff would be pretty small. Moreover, it could eventually be soft-forked away in the future to remove the technical debt created again. (Even though one should allow sufficient time to not lock up money in time-locked transactions)

**Comment by Sjors** [comment] 2017-10-04 10:26
> This won't break anything, it would be completely opt-in

It certainly won't break the sending wallet. It also won't break the receiving wallet if the user doesn't use this feature. But the effect on receiving wallets, when the user does use the feature, needs some research:

1 -  receiving wallet follows 1x chain: it won't receive the transaction, as intended
2 - receiving wallet follows 2x chain: it will receive the transaction, but might consider it invalid depending on how thoroughly it inspects it
  a) this might vary per wallet and per implementation of replay protection
  b) they might treat unconfirmed transactions different

For the SIGHASH type method, one easy way to find out is to study changes made to wallets that successfully implemented BCH (and see if they needed additional changes). This method has also withstood at least some real world testing.

There's some back and forth between me and @xenog elsewhere about what Haskoin does and doesn't check, but that's just one (fairly small) wallet. My guess is that most non fully-validating wallets are happy as long as a transaction is in a block or "the server says so".

**Comment by SoftWarewolf** [comment] 2017-10-07 07:59
I just posted this on the commit, but i am copying it here so it can be heard and considered:

Can we include a de-activation mechanism for this rule? It's unnecessary to permanently increase the technical debt of Bitcoin. It should be trivial to add that after block 500000 or january 1st 2018 or whatever, the rule no longer applies.

I think it's reckless to roll out a consensus upgrade at this point so close to the activation, but i see the value as many businesses will want to rely on this mechanism to split their coins shortly after the fork in the case that both chains survive.

But after a short amount of time enough tainted coins should be available to make this code obsolete. (or it may be obsolete straight away if only one chain survives)

Having a planned deactivation allows easy pruning of code, and prevents any potential or unknown issues that could occur because of this rule in the future.

If necessary it's easier to keep the rule as another soft-fork, than it is to remove it by hard-fork.

**Comment by jcansdale** [comment] 2017-10-08 10:05
@SoftWarewolf,

> Can we include a de-activation mechanism for this rule? It's unnecessary to permanently increase the technical debt of Bitcoin. It should be trivial to add that after block 500000 or january 1st 2018 or whatever, the rule no longer applies.

The intention was always to include a sunset clause for this. The tricky question was how long out to make it. I thought there would be more complaints about a short sunset clause, but it seems that might not be the the case. 😉 

If you'd like to pick up the conversation here, I'd appreciate your input: https://github.com/btc1/bitcoin/pull/127#issuecomment-333407940

I'm now thinking something as short as a month for the consensus rule change. It's really a stop gap measure at the fork point until things settle down.

**Comment by jcansdale** [comment] 2017-10-08 10:13
Has anyone considered the implications of this nLockTime change for transactions sent on the 2x chain?

> Although every transaction contains the nLockTime field, every wallet up until recently set nLockTime to 0, meaning the transaction was valid in any block. Starting with Bitcoin Core 0.11.0, every normal transaction automatically generated by began including an nLockTime set to a recent block height as a way to make hypothesized fee sniping less profitable[1]; other wallets are recommended to do the same.

https://en.bitcoin.it/wiki/Timelock

It appears wallets that implement this change will automatically include a form of replay protection (assuming the 2x chain moves ahead of the 1x chain).

**Comment by Sjors** [comment] 2017-10-10 17:01
See #131 for a possible implementation.

**Comment by BTCgithub** [comment] 2017-10-13 19:07
Please take a moment to read the thread below before considering adding -ANY- replay protection to SegWit2x. It's important that the Legacy 1x chain does -NOT- survive or continue after the 2MB upgrade. Try to ignore the politics and chatter in the thread as there are some good points made regarding the Legacy 1x chain's nodes mempool flooding/circle of death after the upgrade.


'How is 1x even going to survive a 50/50 hash power stand off?'
https://www.reddit.com/r/btc/comments/75xxws/core_shills_how_is_1x_even_going_to_survive_a/?st=j8pj8ati&sh=866e3125

**Comment by apoelstra** [comment] 2017-10-15 09:50
@BTCgithub it is impossible to prevent replay protection. At the moment of the fork if there are blocks on both chains several services (including Ledger, Bitfinex, Xapo and others who have committed to allowing users to access coins on each chain) will split their coins using "natural" methods such as submitting conflicting transactions to each side and hoping that conflicts will confirm. As soon as they have a single split UTXO they are able to split all the rest by Coinjoining.

Absent any deliberate behaviour, this will happen naturally both because of differing confirmation dynamics and because coinbase outputs are inherently single-chain, and as transactions are produced the "single-chain taint" will spread throughout nearly the entire UTXO set of both coins.

There is little purpose served by making this difficult to do deliberately, except to be difficult.

**Comment by bitPico** [comment] 2017-10-15 22:26
NACK

**Comment by jgarzik** [comment] 2017-11-08 20:25
Closing - not needed

**Closed as completed by jgarzik** 2017-11-08 20:25 UTC
